[package]
name = "pwdgen"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = {version = "4.2.2", features = ["derive", "env"]}
anyhow = "1.0.70"